services:
  db:
    image: mongo:6
    restart: unless-stopped
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  api:
    build: /
    container_name: api
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@db:27017/mydb?authSource=admin
    depends_on:
      - db
    ports:
      - "8080:8080"